# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Do not keep production secrets in the repository,
# instead read values from the environment.

development:
  secret_key_base: 4450a9f144844379e2c231a359683f7d2ce5933b736f6ca199257a4707fc940d5d680342bcf64b4f8a12f80405588ec240a96cb740ae7fce25c247626edb5abf

test:
  secret_key_base: ed966bb6668102d6a317a89e53fe3ad455726cb4b02352b26fda8e08ba7380fb7acdbdaca05318998ba682292016514b7be766995aa0bff7d61b012d12be5b2e

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
